### ISSUE TITLE
Couldn't find function overload for 'index' when creating a `RobotWorldConfig` object

### ISSUE THREAD

**Issue by mbusy** [NVlabs/curobo#135]
### Version infromation
1. cuRobo installation mode: `python`
2. python version: `3.8.10`
3. Isaac Sim version (if using): `na`

### Issue details
Hi, when trying to create a `RobotWorldConfig` object using the `load_from_config` method:
```python
# robot_cfg is a valid RobotConfig object, created using from_basic
robot_world_config = RobotWorldConfig.load_from_config(
    robot_config=robot_cfg,
    world_model=None,
)
``` 
I get the following error:
```shell
#############
EXCEPTION WAS RAISED:
Error while parsing function "compute_pose_inverse" at /root/third_party/curobo/src/curobo/geom/transform.py:356:
    out_v[0] = wp.index(out_q, 3)
;Couldn't find function overload for 'index' that matched inputs with types: [warp.types.quatf, int32]
#############
```

### Exploration
It seems that the `0.11.0` version of the `warp` module was released yesterday (24th of January), so I rolled back to version `0.10.1`, I don't have the bug anymore. I don't know if it's relevant or not to open an issue in the warp repo, but this issue is here to let you know that this new warp version might cause crashes

**Comment by balakumar-s** [comment]
This has been fixed in the latest commit. Reopen if the issue still exists.
