### ISSUE TITLE
Attach object in the batch mode

### ISSUE THREAD

**Issue by j-hae1** [NVlabs/curobo#136]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode: python
2. python version: 3.8
3. Isaac Sim version (if using): (using the isaacgym) 

I'm trying to operate the curobo in a batch environment setting, utilizing multiple world files and world configurations. However, I'm encountering a problem when I attempt to attach an object to the robot in batch mode. It seems that this issue may be occurring because the world model is being converted into a list after being configured for batch mode.

------
Issue Details
![image](https://github.com/NVlabs/curobo/assets/59185049/6ae7260d-c886-47e6-a751-73ad33f79b3d)

**Comment by balakumar-s** [comment]
Currently attach object is only supported in non batched mode. See discussion here: https://github.com/NVlabs/curobo/discussions/91#discussioncomment-7925130

**Comment by j-hae1** [comment]
Thank you for quick response!
