### ISSUE TITLE
Shape Mismatch in `_check_none_and_copy_idx`

### ISSUE THREAD

**Issue by cremebrule** [NVlabs/curobo#139]
1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]): isaac sim
2. python version: 3.10
3. Isaac Sim version (if using): 2023.1.1

------
## Issue Details
In a given environment, I've run multiple `plan_batch()` calls which work successfully, given various start / end goal pose configurations (using Franka). However, stochastically I seem to run into the following error:

```
...
<...> in compute_trajectory
    result = self.mg.plan_batch(cu_js_batch, ik_goal_batch, plan_cfg) #.clone())
  File "/home/jdw/projects/repo/curobo/src/curobo/wrap/reacher/motion_gen.py", line 1261, in plan_batch
    result = self._plan_batch_attempts(
  File "/home/jdw/projects/repo/curobo/src/curobo/wrap/reacher/motion_gen.py", line 1165, in _plan_batch_attempts
    best_result.copy_idx(idx, result)
  File "/home/jdw/projects/repo/curobo/src/curobo/wrap/reacher/motion_gen.py", line 701, in copy_idx
    self.position_error = self._check_none_and_copy_idx(
  File "/home/jdw/projects/repo/curobo/src/curobo/wrap/reacher/motion_gen.py", line 680, in _check_none_and_copy_idx
    current_tensor[idx] = source_tensor[idx]
RuntimeError: shape mismatch: value tensor of shape [2] cannot be broadcast to indexing result of shape [2, 1]
```

Any potential insight? I assume it has to do with a problem with some part of the solution failing but I'm quite sure what may be the issue.

Thanks!

**Comment by balakumar-s** [comment]
Is it possible to write an example to reproduce this on our end? We tried running batch planning and didn't hit this issue with the Franka Panda robot.
