### ISSUE TITLE
Usage in Commercial Projects

### ISSUE THREAD

**Issue by OnionIncognito** [NVlabs/curobo#186]
Looking at the results and implementation this really looks fantastic. We would like to evaluate and potentially use in some contracting projects, but we are concern about the license. 

In the license it is stated:

> 3.3 Use Limitation. The Work and any derivative works thereof only may be used or intended for 
use non-commercially. Notwithstanding the foregoing, NVIDIA Corporation and its affiliates may use 
the Work and any derivative works commercially. As used herein, “non-commercially” means for 
research or evaluation purposes only.

Does it mean there is no way for us to integrate in commercial projects? We would like to evaluate cuRobo, but if there is no way for us to later use in commercial projects I don't think we should invest time in the evaluation.

**Comment by balakumar-s** [comment]
To obtain a commercial license, submit this form: https://www.nvidia.com/en-us/research/inquiries/
