### ISSUE TITLE
_run_weight_vec of None type - easy fix

### ISSUE THREAD

**Issue by scharalambous-sony** [NVlabs/curobo#194]
Hi,
I will sometimes get a None type error for _run_weight_vec
https://github.com/NVlabs/curobo/blob/b1f63e8778b9954ed1296f249aceb202ab05e10b/src/curobo/rollout/cost/pose_cost.py#L227

I fixed it by adding these lines right above it:
```
        if self._run_weight_vec is None or self._run_weight_vec.shape[1] != self._horizon:
            self._run_weight_vec = torch.ones(
                (1, self._horizon), device=self.tensor_args.device, dtype=self.tensor_args.dtype
            )
```

**Comment by balakumar-s** [comment]
Fixed
