### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'GetPath'

### ISSUE THREAD

**Issue by starnetB** [NVlabs/curobo#198]
cuRobo installation mode: isaac sim
version: cuda11.7 and isaacsim2022.2.1; cuda11.8 and isaacsim2023.1.1

After setup environment and run example/isaacsim scripts, error occured.
Maybe some packages missed
![Screenshot from 2024-03-23 16-34-40](https://github.com/NVlabs/curobo/assets/66932599/490832e5-a8ac-4dc0-8f31-292e9ae38cfd)

**Comment by starnetB** [comment]
isaacsim2023 pip list:
![Screenshot from 2024-03-23 16-40-28](https://github.com/NVlabs/curobo/assets/66932599/ecb2f97b-9656-46cc-b700-dfe246fb908b)
![Screenshot from 2024-03-23 16-41-49](https://github.com/NVlabs/curobo/assets/66932599/64d6a211-f6cf-4137-939f-8fa509cd00fd)
![Screenshot from 2024-03-23 16-44-06](https://github.com/NVlabs/curobo/assets/66932599/c6987900-7708-49df-b248-ed2b1b7c0065)
![Screenshot from 2024-03-23 16-42-14](https://github.com/NVlabs/curobo/assets/66932599/b49fa422-faed-4d14-bb17-910f6246c851)

**Comment by balakumar-s** [comment]
Does the example work if you pass `--robot ur5e.yml`?

**Comment by starnetB** [comment]
> Does the example work if you pass `--robot ur5e.yml`?

![Screenshot from 2024-03-24 13-23-53](https://github.com/NVlabs/curobo/assets/66932599/09adee43-fc00-4c9e-a0fb-1b1a2b2b6711)

**Comment by starnetB** [comment]
> Does the example work if you pass `--robot ur5e.yml`?

![Screenshot from 2024-03-24 13-36-41](https://github.com/NVlabs/curobo/assets/66932599/da132673-b51c-425f-9e52-969a5179dde9)

**Comment by balakumar-s** [comment]
Did you pip install `usd-core`? There will be one already in the isaac sim environment. If you installed a new version, that can cause issues.

**Comment by starnetB** [comment]
> Did you pip install `usd-core`? There will be one already in the isaac sim environment. If you installed a new version, that can cause issues.
> 
> In addition, is this a remote machine or local machine?

yes, when i install curobo, it said that 'usd-core' missed, so i installed a new one
It's local machine i think

**Comment by balakumar-s** [comment]
Can you uninstall with `pip uninstall usd-core`?

**Comment by starnetB** [comment]
> Can you uninstall with `pip uninstall usd-core`?

im reinstalling isaacsim now, this time it didnt show any message of usd-core. Maybe for the reason of ros environment (this time, i remove ros activate command in ~/.bashrc

**Comment by starnetB** [comment]
![Screenshot from 2024-03-25 15-25-01](https://github.com/NVlabs/curobo/assets/66932599/f0eef44e-f0ad-45b8-9210-372862f4664b)
run with omni_python example/isaac_sim/motion_gen_reacher.py --robot ur5e.yml

**Comment by starnetB** [comment]
I tried install curobo without isaacsim and ran test code, maybe it will give some tips:

![Screenshot from 2024-03-25 16-56-55](https://github.com/NVlabs/curobo/assets/66932599/0fb4d0d2-bba2-41d8-8bd5-c7dc96547244)
![Screenshot from 2024-03-25 16-56-29](https://github.com/NVlabs/curobo/assets/66932599/946de62d-0b5c-4b22-8282-8d4c309e0d58)

**Comment by starnetB** [comment]
Idk the details, but it's actually a network problem

**Comment by chiawenwang** [comment]
> Idk the details, but it's actually a network problem

Hi! I got the same problem about `'NoneType' object has no attribute 'GetPath'`. How did you fix it?

**Comment by MiangChen** [comment]
> > Idk the details, but it's actually a network problem
> 
> Hi! I got the same problem about `'NoneType' object has no attribute 'GetPath'`. How did you fix it?

This may be helpful: https://github.com/isaac-sim/IsaacLab/issues/1814#issuecomment-2661293571

**Comment by explore-code-world7** [comment]
> Idk the details, it's actually a network problem

Yes, I print the prim_path and config, 
then the terrain was imported rightly.

![Image](https://github.com/user-attachments/assets/398d1775-940e-4c32-a819-d958cc6b315e)
