### ISSUE TITLE
The result of compute_smoothness() may be incorrect

### ISSUE THREAD

**Issue by sailuluo** [NVlabs/curobo#222]
![无标题](https://github.com/NVlabs/curobo/assets/49668423/f186174d-7acf-4ecb-814b-90318889c3b9)

The result of”acc_label = torch.logical_and(max_acc_val <= max_acc, max_jerk_val <= max_jerk)“may be incorrect

**Comment by scharalambous-sony** [comment]
Hi, can you try the fix suggested in https://github.com/NVlabs/curobo/pull/217 whether it fixes this issue?

**Comment by sailuluo** [comment]
> Hi, can you try the fix suggested in #217 whether it fixes this issue?

hi，I've tried, issue has been fixed.

**Comment by balakumar-s** [comment]
This has been fixed in the latest release v0.7.2
