### ISSUE TITLE
attach_objects_to_robot/detach_object_from_robot

### ISSUE THREAD

**Issue by Entongsu** [NVlabs/curobo#231]
Hi,

I wonder whether the function `detach_object_from_robot` and `attach_objects_to_robot` support a batch of environments. I have found that the provided example uses these two functions in single environment. Thank you.

**Comment by balakumar-s** [comment]
attaching objects to robot is not supported in batched mode (https://github.com/NVlabs/curobo/discussions/91#discussioncomment-7930459). Unless you are attaching the same object at the same pose across your batch.
