### ISSUE TITLE
Nvblox collision checker demo sometimes gives incorrect results

### ISSUE THREAD

**Issue by wuyingnan** [NVlabs/curobo#255]
Please provide the below information in addition to your issue:

1. cuRobo installation mode (isaac sim) with nvblox installed by source
2. python version: 3.10.13(omni_python)
3. Isaac Sim version : 2023.1.0

------
The sphere sometimes goes to green even if it is close to mesh collision objects.

![new](https://github.com/NVlabs/curobo/assets/5039169/76a88710-6d1d-4b3c-b978-f27eb91c97c5)

**Comment by balakumar-s** [comment]
In this example, we visualize the world as a mesh but use nvblox as the collision checker. We had a numerical precision bug in how the distance was found from nvblox's representation which we have fixed. Check the latest main branch, specifically this example: https://github.com/NVlabs/curobo/blob/ec527d77e99d4b4bd3579833a033a1bb674bf3c4/benchmark/curobo_voxel_benchmark.py#L310
