### ISSUE TITLE
UserWarning occurred when testing motion generation 

### ISSUE THREAD

**Issue by zipping-suger** [NVlabs/curobo#270]
1. cuRobo installation mode: python
2. python version: Python 3.9.19
3. Isaac Sim version (if using): not used 
4.  torch version: 1.13.0+cu116

------
Description:
When testing Motion Generation, I found certain Motionconfig may result in this warning: 
```
UserWarning: FALLBACK path has been taken inside: runCudaFusionGroup. This is an indication that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
 (Triggered internally at ../torch/csrc/jit/codegen/cuda/manager.cpp:331.)
  return compute_distance_norm_jit(pt, batch_pts, self.distance_weight)
tensor([0.0528], device='cuda:0') tensor([1.4793], device='cuda:0') tensor([0.7396], device='cuda:0')
Trajectory Generated:  tensor([True], device='cuda:0') 0.04400944709777832 None tensor([0.0264], device='cuda:0')
```
It seems not to affect the result.  But I am not very sure.

A simple way to reproduce this issue is to change the **185** line of file `examples/motion_gen_example.py` from `robot_file = "franka.yml"` to ` robot_file = "ur5e.yml"`. Then run `python examples/motion_gen_example.py`

**Comment by balakumar-s** [comment]
This is coming from pytorch's jit compiler and does not affect cuRobo's performance.
