### ISSUE TITLE
Will curobo support omniverse-orbit in the future?

### ISSUE THREAD

**Issue by pmj110119** [NVlabs/curobo#283]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]):
2. python version:
3. Isaac Sim version (if using): 

------
Issue Details

**Comment by balakumar-s** [comment]
cuRobo can be used in omniverse-orbit as cuRobo is a python library. However, we don't plan to have examples showing how to integrate. The closest starting point would be to look at isaac sim examples: https://curobo.org/get_started/2b_isaacsim_examples.html
