### ISSUE TITLE
Documentation is missing a `cd ./curobo` before `pip install -e . --no-build-isolation`

### ISSUE THREAD

**Issue by AndyZe** [NVlabs/curobo#297]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode: python
2. python version: 3.10.12

------
Issue Details

Referring to this page:  https://curobo.org/get_started/1_install_instructions.html

This text:

Clone cuRobo repository with git clone https://github.com/NVlabs/curobo.git and run pip install -e . --no-build-isolation.

Should be something like:

Clone cuRobo repository with `git clone https://github.com/NVlabs/curobo.git`. From the curobo directory, run `pip install -e . --no-build-isolation`

(a `cd` command is missing)

**Comment by balakumar-s** [comment]
Fixed in latest  commit.
