### ISSUE TITLE
A collection of bug fixes to run successfully in Docker Isaac Sim

### ISSUE THREAD

**Issue by j3soon** [NVlabs/curobo#302]
1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]): docker isaac sim
2. python version: Python 3.10.13
3. Isaac Sim version (if using): 2023.1.0

------
Issue Details:

- Use `isaac-3.0` branch
  ```sh
  git clone git@github.com:NVlabs/curobo.git
  cd curobo
  git checkout isaac-3.0
  ```
  Ref: https://github.com/NVlabs/curobo/issues/301
- Modify the Dockerfile to use the `isaac-3.0` branch
  ```sh
  cd docker
  vim isaac_sim.dockerfile
  ```
  
  Modify the Dockerfile from:
  
  ```
  # COPY pkgs /pkgs

  RUN mkdir /pkgs && cd /pkgs && git clone https://github.com/NVlabs/curobo.git
  ```
  to:
  
  ```
  COPY pkgs /pkgs

  # RUN mkdir /pkgs && cd /pkgs && git clone https://github.com/NVlabs/curobo.git
  ```
  
  exit vim and clone the repo again:
  
  ```
  mkdir pkgs
  cd pkgs
  git clone git@github.com:NVlabs/curobo.git
  cd curobo
  git checkout isaac-3.0
  cd ../../..
  ```
  Ref: https://github.com/NVlabs/curobo/blob/0c51dd2da8d4a76ebaa0dee4e302ef88e504bce0/docker/isaac_sim.dockerfile#L168-L174
  Ref: https://github.com/NVlabs/curobo/blob/0c51dd2da8d4a76ebaa0dee4e302ef88e504bce0/docker/x86.dockerfile#L86-L92
- Fix `omni_python` alias
  ```sh
  cd docker
  vim isaac_sim.dockerfile
  ```
  
  Modify the Dockerfile from:
  
  ```
  RUN echo "alias omni_python='/isaac-sim/python.sh'" >> /.bashrc
  ```
  
  to:
  
  ```
  RUN echo "alias omni_python='/isaac-sim/python.sh'" >> ~/.bashrc
  ```
  Ref: https://github.com/NVlabs/curobo/blob/0c51dd2da8d4a76ebaa0dee4e302ef88e504bce0/docker/isaac_sim.dockerfile#L160
- Build and launch the docker container (No changes here)
  ```sh
  cd docker
  TAG=isaac_sim_2023.1.0
  bash build_docker.sh $TAG
  xhost +local:docker
  bash start_docker.sh $TAG
  ```
  Ref: https://curobo.org/get_started/5_docker_development.html
- Run the Isaac Sim examples
  ```sh
  omni_python examples/isaac_sim/collision_checker.py
  omni_python examples/isaac_sim/motion_gen_reacher.py --robot franka.yml
  ```
  Note that the commands here are different from those written in the docs. I think the code is updated while the docs weren't updated accordingly.

  Ref: https://curobo.org/get_started/2b_isaacsim_examples.html
  > Launch `omni_python examples/isaac_sim/collision_checker_example.py` to run a collision checking example.
  > ...
  > Launch `omni_python examples/isaac_sim/motion_gen_reacher.py --robot franka`, which will load the Franka Panda robot and a red cube similar to the UI above.

**Comment by balakumar-s** [comment]
We have updated our docker steps based on your suggestions.
