### ISSUE TITLE
Using CuRobo with ROS2 Foxy

### ISSUE THREAD

**Issue by LuCarpentier92** [NVlabs/curobo#307]
### Discussed in https://github.com/NVlabs/curobo/discussions/305

<div type='discussions-op-text'>

<sup>Originally posted by **LuCarpentier92** June 20, 2024</sup>
Hello,

I am currently trying to use CuRobo to control a Doosan M1013. I have set up a Docker environment for CuRobo and I am interested in how to publish velocity commands generated by CuRobo to a ROS2 topic.

I have attempted to create a package where I implemented a node to launch the motion_gen_reacher.py example, but it has not been successful. The issue may be related to the Python interpreter not being set correctly (I tried referencing omni_python without success).

Please let me know if you have any tips or suggestions to assist with this.

Thanks :0</div>

**Comment by balakumar-s** [comment]
Moving to discussion: https://github.com/NVlabs/curobo/discussions/305
