### ISSUE TITLE
Does cuRobo support robot with prismatic joint?

### ISSUE THREAD

**Issue by Shimadawallace** [NVlabs/curobo#359]
Hi, I want to apply cuRobo's motion generation to Hello Robot (https://hello-robot.com/) which has several prismatic joints, so I changed one of the revolute joint of ure5 to prismatic joint to see whether cuRobo supports primatic joint or not.
I found that after the changing, the ure5 robot in isaac sim don't move any more.
Could you tell me is it possible to apply cuRobo on a robot with prismatic joint? if not, could you tell me the reason?

**Comment by Shimadawallace** [comment]
it's working with Panda robot with prismatic joint now

**Comment by balakumar-s** [comment]
Also see here for an example yml configuration for the stretch robot: https://github.com/NVlabs/curobo/discussions/146#discussioncomment-8402647
