### ISSUE TITLE
Error  when run "motion_gen_reacher.py"

### ISSUE THREAD

**Issue by peter05010402** [NVlabs/curobo#41]
Hi,
my env info:
1. cuRobo installation mode:     python, isaac sim
2. python version:                      3.7.13
3. Isaac Sim version (if using):  2022.2.1

------
Issue Details:
When run motion_gen_reacher.py on my robot without griper collision spheres,  It's workable.
But with griper collision spheres, it got Error:
![img_v3_0257_9d35dfbe-352f-47b4-b6bd-bc62269c7cdg](https://github.com/NVlabs/curobo/assets/42974031/7656256c-bf91-45da-8177-f6d8be42d928)

**Comment by peter05010402** [comment]
Is this lead to the error:
![image](https://github.com/NVlabs/curobo/assets/42974031/f1f3d290-eba4-431f-868f-bef3c1294341)

**Comment by balakumar-s** [comment]
Does the standard examples work (with the franka.yml robot)  in the same python environment?
I am asking because I see `Failed to load CUDA module` in your log which is not related to  a robot configuration.

**Comment by peter05010402** [comment]
yes, standard example work.   
It failed ,because of wrong robot configuration!
Thank you for ur reply
