### ISSUE TITLE
Error when building docker

### ISSUE THREAD

**Issue by pmj110119** [NVlabs/curobo#63]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]):  python
2. python version:    3.8
3. Isaac Sim version (if using): No

------
Issue Details

I can't build docker through the docker/*.sh, please help me >.<

**My command:**
```
bash docker/build_dev_docker.sh
```
**Error Result:** 
```
deprecated, use build_docker.sh instead
Argument empty, trying to build based on architecture
Building for X86 Architecture
x86.dockerfile
[+] Building 0.0s (2/2) FINISHED                                         docker:default
 => [internal] load .dockerignore                                                  0.0s
 => => transferring context: 2B                                                    0.0s
 => [internal] load build definition from x86.dockerfile          0.0s
 => => transferring dockerfile: 2B                                         0.0s
ERROR: failed to solve: failed to read dockerfile: open /data/docker/tmp/buildkit-mount2339691937/x86.dockerfile: no such file or directory
```

**Comment by balakumar-s** [comment]
Is this on a windows machine? If it's linux, what is the version of linux and docker you are using?

**Comment by pmj110119** [comment]
Thanks for reply, my env: Ubuntu 20.04，Docker version 24.0.7

**Comment by balakumar-s** [comment]
You have to be in the docker folder to run the script. Try with `cd docker && bash build_docker.sh`
