### ISSUE TITLE
About adding sphere in configuration

### ISSUE THREAD

**Issue by Spphire** [NVlabs/curobo#71]
1. cuRobo installation mode [isaac sim]:
2. python version: default
3. Isaac Sim version : 2023

When I adding sphere in part of configuration custom robot, I found that if some link of urdf have a refer mesh file with scale<0, like this:

```
<geometry>
<mesh filename="meshes/dhag95/visual/proximal_phalanx_link.STL" scale="0.001 0.001 0.001" />
</geometry>
```

the spheres added automatedly are huge and at wrong position, and "scale spheres in link" panel cant solve the problem

**Comment by balakumar-s** [comment]
This could be a bug in the robot sphere generator in Isaac Sim. I will try to reproduce this and pass it along to the Isaac Sim team.
