### ISSUE TITLE
Error when use shadowhand robot

### ISSUE THREAD

**Issue by Spphire** [NVlabs/curobo#76]
Isaac Sim version 2023

The reason might be too many sphere collisions?
![image](https://github.com/NVlabs/curobo/assets/56157591/ccedbe32-c3c4-4245-9faa-27b9fdc281cc)

[config.zip](https://github.com/NVlabs/curobo/files/13642958/config.zip)

**Comment by balakumar-s** [comment]
We fixed a bug that could have been the cause of this issue. Can you try with the latest commit on main branch? Once you download the latest commit, recompile the package with `omni_python -m pip install -e . --no-build-isolation`

**Comment by Spphire** [comment]
> We fixed a bug that could have been the cause of this issue. Can you try with the latest commit on main branch? Once you download the latest commit, recompile the package with `omni_python -m pip install -e . --no-build-isolation`

cant install it
![image](https://github.com/NVlabs/curobo/assets/56157591/e1ca9b39-375a-498b-96ce-2af35fe68b04)

**Comment by balakumar-s** [comment]
It looks like git didn't clone the repo correctly. Can you clone the repo into a new folder and try again?
Also make sure you have the following installed `omni_python -m pip install tomli wheel ninja`

**Comment by Spphire** [comment]
It's fixed!
