### ISSUE TITLE
CuRobo loads unscaled meshes

### ISSUE THREAD

**Issue by waldezjr** [NVlabs/curobo#79]
After adding a mesh file to the World Configuration, CuRobo effectively loads the unscaled mesh.

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]): python
2. python version: 3.10
3. Isaac Sim version (if using): 

------
Issue Details

I tried adding a simple sphere mesh through a yml file
 sphMesh:
     pose: [0.0, 0, 0.15, 1, 0, 0, 0]
     scale: [0.005, 0.005, 0.005]
     file_path: "sphere_mesh.obj"
     
And loading it as in the script below

```python
with open(model.config["curoboConfig"]["worldYmlPath"]) as file_p:
            worldCfg = yaml.load(file_p, Loader=Loader)
world_model = WorldConfig.from_dict(worldCfg)
world_model.save_world_as_mesh("debugMesh.obj")
```

But when I load the debugMesh.obj file in a 3rd party viewer I verify that the object, as seen by CuRobo, is not scaled.

ps.: It is not a major issue, but it may be useful to solve it eventually

**Comment by balakumar-s** [comment]
Thanks for catching this. Internally, the mesh was actually being scaled but when exporting the world model, the scaling was not being applied. This has been fixed in the latest commit.
